version: '3'
services:
  frontend:
    image: node:18.15.0-slim
    environment:
      - WATCHPACK_POLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: > 
      bash -c "yarn && yarn start"
    ports:
      - ${HOST_IP}:${HOST_PORT}:3000
    env_file:
      - .env
    stdin_open: true

volumes:
  node_modules:
